### ISSUE TITLE
Peptide Shaker not showing any results

### ISSUE THREAD

**Issue by subinamehta** [compomics/searchgui#203]
I am using Search Gui v3.3.3.0 in Galaxy and Peptide Shaker v1.16.26. 
When I run 4 Search Engines, the SG works but Peptide Shaker doesn't provide results (although it doesn't fail). Thus no error report. It reports 0 lines. I have pasted the log file here:

> 

 inflated: SEARCHGUI_IdentificationParameters.par
Path configuration completed.
Sat Feb 09 20:03:45 CST 2019 Unzipping searchgui_input.zip.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%

Sat Feb 09 20:04:16 CST 2019 Import process for Galaxy_Experiment_2019020920031549764186 (Sample: Sample_2019020920031549764186, Replicate: 1)

Sat Feb 09 20:04:16 CST 2019 Importing sequences from input_database.fasta.
Reindexing: input_database.fasta.
10% 20% 30% 40% 50% 60% 70% 80% 90% 0%
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sat Feb 09 20:04:57 CST 2019 FASTA file import completed.
Sat Feb 09 20:04:57 CST 2019 Establishing local database connection.
Sat Feb 09 20:05:04 CST 2019 Reading identification files.
Sat Feb 09 20:05:04 CST 2019 Parsing ABRF_2016_40Y_1_Sample3.msgf.mzid.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sat Feb 09 20:05:19 CST 2019 Loading spectra for ABRF_2016_40Y_1_Sample3.msgf.mzid.
Sat Feb 09 20:05:19 CST 2019 Importing ABRF_2016_40Y_1_Sample3.mgf
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:06:14 CST 2019 ABRF_2016_40Y_1_Sample3.mgf imported.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:06:15 CST 2019 Collecting peptides to map.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sat Feb 09 20:06:15 CST 2019 Mapping peptides to proteins.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sat Feb 09 20:06:17 CST 2019 Importing PSMs from ABRF_2016_40Y_1_Sample3.msgf.mzid
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:06:21 CST 2019 4 identified spectra (0.0%) did not present a valid peptide.
Sat Feb 09 20:06:21 CST 2019 60 of the best scoring peptides were excluded by the import filters:
Sat Feb 09 20:06:21 CST 2019     - 83.3% peptide mapping to both target and decoy.
Sat Feb 09 20:06:21 CST 2019     - 16.7% peptide presenting high mass or isotopic deviation.
Sat Feb 09 20:06:21 CST 2019 Parsing ABRF_2016_40Y_1_Sample3.t.xml.
Sat Feb 09 20:07:42 CST 2019 Loading spectra for ABRF_2016_40Y_1_Sample3.t.xml.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sat Feb 09 20:07:42 CST 2019 Collecting peptides to map.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sat Feb 09 20:07:42 CST 2019 Mapping peptides to proteins.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sat Feb 09 20:07:43 CST 2019 Importing PSMs from ABRF_2016_40Y_1_Sample3.t.xml
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:07:43 CST 2019 235 identified spectra (0.3%) did not present a valid peptide.
Sat Feb 09 20:07:43 CST 2019 307 of the best scoring peptides were excluded by the import filters:
Sat Feb 09 20:07:43 CST 2019     - 100.0% peptide mapping to both target and decoy.
Sat Feb 09 20:07:43 CST 2019 File import completed. 137803 first hits imported (678082 secondary) from 72870 spectra.
Sat Feb 09 20:07:43 CST 2019 [137343 first hits passed the initial filtering]
Sat Feb 09 20:07:43 CST 2019 Computing assumptions probabilities.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 110% 120% 130% 140% 150% 160% 170% 180% 190% 200%
Sat Feb 09 20:07:44 CST 2019 Saving assumptions probabilities.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:07:46 CST 2019 Selecting best peptide per spectrum.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:07:50 CST 2019 Computing PSM probabilities.
10% 20% 30% 40% 50% 60% 70% 80%
Sat Feb 09 20:07:50 CST 2019 Scoring PTMs in PSMs (D-score and A-score)
Sat Feb 09 20:07:50 CST 2019 Scoring PSM PTMs. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:08:06 CST 2019 Resolving peptide inference issues.
Sat Feb 09 20:08:06 CST 2019 Peptide Inference. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:08:10 CST 2019 Saving probabilities, building peptides and proteins.
Sat Feb 09 20:08:10 CST 2019 Attaching Spectrum Probabilities - Building Peptides and Proteins. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:08:11 CST 2019 Simplifying protein groups.
Sat Feb 09 20:08:11 CST 2019 Symplifying Protein Groups. Please Wait...
10% 20% 30% 40% 50%
Sat Feb 09 20:08:13 CST 2019 Removing Mapping Artifacts. Please Wait...
Sat Feb 09 20:08:13 CST 2019 1128 unlikely protein mappings found:
Sat Feb 09 20:08:13 CST 2019     - 566 protein groups supported by non-enzymatic shared peptides.
Sat Feb 09 20:08:13 CST 2019     - 155 protein groups explained by peptides shared to less confident mappings.
Sat Feb 09 20:08:13 CST 2019     - 10 protein groups supported by peptides shared to uncharacterized proteins.
Sat Feb 09 20:08:13 CST 2019     - 742 groups explained by a simpler group.
Sat Feb 09 20:08:13 CST 2019     Note: a group can present combinations of these criteria.
Sat Feb 09 20:08:13 CST 2019 Generating peptide map.
Sat Feb 09 20:08:13 CST 2019 Filling Peptide Maps. Please Wait...
10% 20% 30% 40%
Sat Feb 09 20:08:14 CST 2019 Computing peptide probabilities.
Sat Feb 09 20:08:14 CST 2019 Estimating Probabilities. Please Wait...
10% 20% 30% 40% 50% 60% 70%
Sat Feb 09 20:08:14 CST 2019 Saving peptide probabilities.
Sat Feb 09 20:08:14 CST 2019 Attaching Peptide Probabilities. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:08:14 CST 2019 Generating protein map.
Sat Feb 09 20:08:14 CST 2019 Filling Protein Map. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:08:14 CST 2019 Resolving protein inference issues, inferring peptide and protein PI status.
Sat Feb 09 20:08:14 CST 2019 Simplifying Redundant Protein Groups. Please Wait...
10%
Sat Feb 09 20:13:41 CST 2019 Inferring PI status, sorting proteins. Please Wait...
 20% 30% 40% 50% 60%
Sat Feb 09 20:13:44 CST 2019 17021 conflicts resolved. 10807 protein groups remaining (58 suspicious).
Sat Feb 09 20:13:44 CST 2019 Correcting protein probabilities.
Sat Feb 09 20:13:44 CST 2019 Estimating Probabilities. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sat Feb 09 20:13:44 CST 2019 Saving protein probabilities.
Sat Feb 09 20:13:44 CST 2019 Attaching Protein Probabilities. Please Wait...
10%Reindexing: input_database.fasta.
 20% 30%Reindexing: input_database.fasta.
 40%Reindexing: input_database.fasta.
 50%Reindexing: input_database.fasta.
 60%Reindexing: input_database.fasta.
 70%Reindexing: input_database.fasta.
 80% 90%
Sat Feb 09 20:14:05 CST 2019 Validating identifications at 1% FDR, quality control of matches.
Sat Feb 09 20:14:05 CST 2019 Finding FDR Thresholds. Please Wait...
10% 20% 40% 50% 70% 80% 100% 110% 120%
Sat Feb 09 20:14:05 CST 2019 Match Validation and Quality Control. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sat Feb 09 20:14:55 CST 2019 Scoring PTMs in peptides.
Sat Feb 09 20:14:55 CST 2019 Scoring Peptide PTMs. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:14:57 CST 2019 Scoring PTMs in proteins.
Sat Feb 09 20:14:57 CST 2019 Scoring Protein PTMs. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:14:58 CST 2019 Identification processing completed (10 minutes 42.0 seconds).

Sat Feb 09 20:14:58 CST 2019 Project successfully created.
Sat Feb 09 20:14:58 CST 2019 Saving results.
10% 20% 30% 40% 50% 60% 70% 80% 90%
Sat Feb 09 20:17:13 CST 2019 Results saved to /panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/job_working_directory/000/191/191355/working/peptideshaker_output.cpsx.

Sat Feb 09 20:17:13 CST 2019 Starting report export.
Sat Feb 09 20:17:13 CST 2019 Exporting. Please Wait...
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Sat Feb 09 20:20:04 CST 2019 Exporting. Please Wait...
10%
PeptideShaker project (.cpsx or .zip file) '/panfs/roc/website/galaxyp.msi.umn.edu/GALAXYP/database/job_working_directory/000/191/191355/working/peptideshaker_output.zip' not found.

>

**Comment by CarlosHorro** [comment]
Hi subinamehta,

In order to reproduce the problem in the best possible way, I would need to know which search engines are you using in SG, and if all this workflow (SG + PS) is executed on Galaxy as it seems by the log.

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
I've tested SG v3.3.3.0 + PS v1.16.26 running on on Galaxy  with a dataset we usually use for testing, and uniprot-human-reviewed-june-2018.fasta with default configurations running XTandem, MSGF+, OMSSA and Tide, and PS returned proper results. Therefore, I think that the problem may be caused by 1) bad management by PS of empty results under certain circumstances or 2) bad management by SG+PS of a specific combination of configurations and/output selections. 
I've tried some different combinations but still I didn't manage to reproduce the problem. Could you please tell me which output options you checked on PS?

**Comment by subinamehta** [comment]
Hi Carlos,
The search engines I used we Xtandem, MSGF+, OMSSA and Comet.

Subina

**Comment by CarlosHorro** [comment]
Hi Subina,

As I said, it would also be necessary to know the specific configurations and output selections you checked in order to be able to reproduce the problem.
But, before doing this, I would strongly recommend you to update your Galaxy tools (SG and PS) to the last ones (PS 1.16.36.2 and SG 3.3.10.1, released on last January 16th.), as your versions are quite old and many of their bugs may have been solved in the new ones, and execute your workflow again with them. 
I will help you if you have any problem with this entire procedure.

Greetings,
Carlos

**Comment by subinamehta** [comment]
Hi Carlos,

I will get it updated in Galaxy and let you know if I still get the same error!

Subina

**Comment by CarlosHorro** [comment]
Could you tell us if the error has finally been solved in order to close this issue, please?

**Comment by subinamehta** [comment]
This error has been resolved with the new version.. Thanks
