### ISSUE TITLE
MSAmanda and Myrimatch do not work in latest SearchGUI Docker distribution

### ISSUE THREAD

**Issue by MaxAlex** [compomics/searchgui#305]
On the newest version of the docker image on Biocontainers (quay.io/biocontainers/searchgui:4.0.33--h779adbc_0 found at https://biocontainers.pro/tools/searchgui), MS Amanda and Myrimatch are not executing correctly.  Namely;

MS Amanda does not run; even trying to run the program with a command such as
`docker run quay.io/biocontainers/searchgui:4.0.33--h779adbc_0 mono "/usr/local/share/searchgui-4.0.33-0/resources/MS Amanda/MSAmanda.exe"`
gives the error
`Cannot open assembly '/usr/local/share/searchgui-4.0.33-0/resources/MS Amanda/MSAmanda.exe': File does not contain a valid CIL image.`

Myrimatch does run and executes a search, but does not produce a result file.  Here is a sample terminal output:
```
Process #0 (db8229e54734) is starting.
MyriMatch 2.2.10165 (2016-11-7)
FreiCore 1.6.11103 (2017-7-14)
ProteoWizard MSData 3.0.11841 (2018-3-8)
ProteoWizard Proteome 3.0.11579 (2017-11-14)
Vanderbilt University (c) 2012, D.Tabb/M.Chambers/S.Dasari
Licensed under the Apache License, Version 2.0

Could not find the default configuration file (hard-coded defaults in use).
Reading "/data/K562_Analysis_miniSG_K562_searchGUI_analysis/human_UniProt_wDecoy.fasta"
Read 524922 proteins; 0.538816 seconds elapsed.
Reading spectra from file "/data/tempfiles/K562_Analysis_miniSG_K562_searchGUI_analysis/peak_lists/20100614_Velos1_TaGe_SA_K562_6.raw.mgf"
myrimatch: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.


Wed Jun 16 05:15:23 GMT 2021 MyriMatch finished for 20100614_Velos1_TaGe_SA_K562_6.raw.mgf (775.0 milliseconds).

Wed Jun 16 05:15:23 GMT 2021 Could not find MyriMatch result file for 20100614_Velos1_TaGe_SA_K562_6.raw.mgf.
```

Going back to an earlier version of the container (I tried quay.io/biocontainers/searchgui:4.0.4--h516909a_0) avoids these issues.  The host machine executing the docker image is a standard Ubuntu 20:04 image on an AWS instance.  I gather this is a problem with the docker packaging rather than searchGUI itself, so if that isn't maintained by the same folks please disregard this bug report.

Thanks!

**Comment by MaxAlex** [comment]
An addendum to the above; for reasons possibly unrelated, OMSSA also does not work in Docker images I've tried; this error occurs even in the 4.0.4 version which has a working MS Amanda and Myrimatch.  (I forgot about this one since, IIRC, it hasn't worked since I started using SearchGUI.)

OMSSA fails with the message
`/usr/local/share/searchgui-4.0.4-0/resources/makeblastdb/linux/linux_64bit/makeblastdb: error while loading shared libraries: libbz2.so.1: cannot open shared object file: No such file or directory`

Again, this is occurring at least for quay.io/biocontainers/searchgui:4.0.33--h779adbc_0 and :4.0.4--h516909a_0 , on the same Ubuntu 20.04 AWS instance host as the previous issue.

Thanks again.

**Comment by CarlosHorro** [comment]
Hi @MaxAlex ,

We have some hypothesis about the cause of these problems, but I'm quite surprised about the fact that they seemed to work in older versions.
Looking into this may require some time but I will try to do it.

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
Hi @MaxAlex ,

I just wanted to clarify that we are working on this and we have found the cause of MsAmanda problem (they have moved their project to .NET core platform). SG app itself will be deployed soon with this fix, although the Docker container, conda package and Galaxy tool may require some time to be updated.

We will keep you updated about all other issues you reported.
Greetings,
Carlos

**Comment by MaxAlex** [comment]
Excellent, thanks!  I look forward to the new version.

**Comment by CarlosHorro** [comment]
Hi @MaxAlex ,

Today a new version of SearchGUI application has been released solving MSAmanda problem. We will still need time to update the Conda package, Docker container and Galaxy tool to this last version. 
Myrimatch and OMSSA bugs will also be fixed in those releases when they are available.

Greetings,
Carlos

**Comment by MaxAlex** [comment]
Thanks again!

Another question related to all of this; since Andromeda is typically supported on Windows only, would this be expected to work in the Docker image?  I notice that it's available in the image, but it also results in an error when run.

**Comment by CarlosHorro** [comment]
Hi @MaxAlex ,

We have been trying to support Andromeda in Linux/MacOS using mono/dotnet for a long time, but it has not been possible due to different issues, so it is normal that it throws an error when trying to execute it into a container.

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
Hi @MaxAlex ,

We have finally released new versions of SearchGUI (v4.0.41) and PeptideShaker (v2.0.29) Conda packages and Docker containers. The Galaxy tools are not ready yet, but I think you were more interested on the containers :-)

Greetings,
Carlos

**Comment by MaxAlex** [comment]
Thanks again for your hard work.  Something might still not be right, though- now using the updated container, `quay.io/biocontainers/searchgui:4.0.41--h779adbc_0`, MS Amanda now throws a different error;

```
Failure processing application bundle.
Bundle header version compatibility check failed
A fatal error was encountered. Could not extract contents of the bundle
```

And Myrimatch also throws an error, also different from before;

```
myrimatch: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
```

**Comment by CarlosHorro** [comment]
Hi @MaxAlex , 

Thank you very much for your highly valuable feedback, I was recently aware of the new Ms Amanda problem but I really thought that Myrimatch bugfix was working, so I must have missed something there too.
I will contact you again as soon as there are news about this all.

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
Hi @MaxAlex ,

We have released new versions of SearchGUI and PeptideShaker Conda packages, Docker containers and Galaxy tools which must solve all previously commented issues:

- SearchGUI 4.0.41.1
- PeptideShaker 2.0.33

I hope they will work for you as expected.

Greetings,
Carlos

**Comment by MaxAlex** [comment]
I've just now gotten a chance to test the updated version; Myrimatch appears to work but MSAmanda searches are failing with a new error, namely
```
/usr/local/share/searchgui-4.0.41-1/resources/MS Amanda/linux/MSAmanda: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by CarlosHorro** [comment]
Hi @MaxAlex ,

Sorry for the inconveniences, I was aware of the possibility of that type of problem but I supposed it would happen in rare occasions... I guess I was wrong...
This one is a more complicated problem to solve... we will see what can be done.

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
> I've just now gotten a chance to test the updated version; Myrimatch appears to work but MSAmanda searches are failing with a new error, namely
> 
> ```
> /usr/local/share/searchgui-4.0.41-1/resources/MS Amanda/linux/MSAmanda: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
> ```

Hi @MaxAlex , I'm sorry to say that the cause of this error is out of our hands as it is a bioconda-related issue when creating the Conda package (and using the last MS Amanda version). It could be solved if there was a MS Amanda Conda package, but there isn't..
So, I'm afraid that the only way to bypass this issue is to use an older version of SearchGUI (with an older version of MS Amanda). The last one with MS Amanda depending on the previous framework is SG 4.0.22.

Greetings,
Carlos
